### ISSUE TITLE
Timebox disrespect warning

### ISSUE THREAD

**Issue by ceci** [agile-alliance-brazil/submissions#168]
**In order to...** allow us to apply penalties to authors that don't respect their assigned time slots
**As...** Program committee member 
**I want...** to make it really clear to authors that sanctions can be applied on the next submission process on those authors who use more time than assigned to them. This warning needs to be added both on the Guidelines section and the Author confirmation e-mail.

**Comment by hugocorbucci** [comment]
Do you have the text in PT and EN? :)

**Comment by ceci** [comment]
I think 3c17aee9224f941912a07116b246a2cc7583cb24 solved it, and I forgot to close this.
