### ISSUE TITLE
Comment ranking

### ISSUE THREAD

**Issue by ceci** [agile-alliance-brazil/submissions#170]
**In order to...** get more feedback from everyone so that I can improve my session proposal before submissions' deadline 
**As...** an author 
**I want...** to incentivise people to comment on mine and others' submissions through a ranking. Every time someone comments on a proposal, they get 1 point, and that the top commenters can be shown at agilebrazil.com (public API?) :-)

**Comment by hugocorbucci** [comment]
Is this separated by year?
Or is it just top commenters overall? Top how many?

**Comment by ceci** [comment]
We probably won't need this either. :-)
