### ISSUE TITLE
Dynamic Help Text

### ISSUE THREAD

**Issue by ceci** [agile-alliance-brazil/submissions#171]
**In order to...** know the purpose of each one of my submissions' fields, and avoid getting bad feedback from reviewers for silly stuff
**As...** an author
**I want...** the submission page to show only the help text of the field I am currently focusing on, with useful information about what I should pay attention to while filling that information.

Storyboard at https://dl.dropboxusercontent.com/u/9092538/help-text-storyboard.jpg

**Comment by hugocorbucci** [comment]
Should this be closed due to #175?

**Comment by ceci** [comment]
Precisely! Closed on #175
