### ISSUE TITLE
Bundled VM is not working properly

### ISSUE THREAD

**Issue by lcobucci** [agile-alliance-brazil/submissions#195]
I was unable to run the VM due to a problem. It seems to be related to the puppet configuration: https://gist.github.com/lcobucci/d1623c04bca7f14f1701

**My environment:**
Ubuntu 15.04 amd64
Vagrant 1.7.2
VirtualBox 4.3.26

**Comment by hugocorbucci** [comment]
This might have been solved once we gave up on librarian puppet in df60afd01f3a760bf00c2b0adb8dff0ad07b49df.

Please try again. More info on the [README](https://github.com/agile-alliance-brazil/submissions/blob/master/README.md) now too.

**Comment by hugocorbucci** [comment]
Never heard again so I'm just closing this one. Please re-open if you have more problems
