### ISSUE TITLE
API for getting approved sessions

### ISSUE THREAD

**Issue by ceci** [agile-alliance-brazil/submissions#200]
**In order to...** get the data I need to generate the conference schedule with rooms and dates using our [Schedule Builder](https://github.com/agile-alliance-brazil/scheduleBuilder)
**As...** program chair and Schedule Builder maintainer
**I want...** the submission system API to export a list with all accepted sessions' data

**Comment by hugocorbucci** [comment]
API is available under:
`<host>/api/(<year>/)sessions/accepted.json`

For example:
`https://submissoes-staging.agilebrazil.com/api/2015/sessions/accepted.json`
or
```curl "https://submissoes-staging.agilebrazil.com/api/2015/sessions/accepted.json"```

**Comment by hugocorbucci** [comment]
It is also available under JSONP for AJAX requests format under:
`<host>/api/(<year>/)sessions/accepted.js?callback=myFunction`

For example:
`curl -H 'X-Requested-With: XMLHttpRequest' "https://submissoes-staging.agilebrazil.com/api/2015/sessions/accepted.js?callback=myFunction"`
