### ISSUE TITLE
Updating a session with 2 authors while being the second author errors out

### ISSUE THREAD

**Issue by hugocorbucci** [agile-alliance-brazil/submissions#201]
Problem is that when the second author is editing, the inferred_params that get merged in https://github.com/agile-alliance-brazil/submissions/blob/master/app/controllers/sessions_controller.rb#L73 is incorrect.

Need more logic for this to work.

**Comment by ceci** [comment]
How did you find that out?

**Comment by hugocorbucci** [comment]
Alex Freire reported and I looked at the code a bit ;)

Hugo Corbucci
Skype user: hugo.corbucci
Twitter: hugocorbucci

On Mon, Feb 29, 2016 at 5:53 PM, Cecilia Fernandes <notifications@github.com
