### ISSUE TITLE
Audience type "all"

### ISSUE THREAD

**Issue by ericabriones** [agile-alliance-brazil/submissions#205]
**As an....** author
**I want to....** have the option to say that my session is for all audience types
**In order to...** properly submit my session, since sometimes what I have to say serves several types of audiences and whatever audience type I choose won't make sense either way.

Examples of this problem, Érica's and Ceci's submissions for 2015:
O que eu aprendi trabalhando na organização do Agile Brazil - https://submissoes.agilebrazil.com/2015/sessions/1338
Voluntários na Agile Brazil: criando um time em seis horas! - https://submissoes.agilebrazil.com/2015/sessions/1339

**Comment by hugocorbucci** [comment]
With the new capability to edit audience levels at will, this will end up being just another audience level that can be registered per conference.
So I'm closing this...
