### ISSUE TITLE
Planilha de extração

### ISSUE THREAD

**Issue by ericabriones** [agile-alliance-brazil/submissions#208]
**Filtros extração:**
- Ano: Possibilidade de extrair os últimos 3 anos considerando o ano da conferência, por exemplo, no ambiente desse ano teríamos os filtros: 2016, 2015 e 2014. Se entrássemos no ambiente do ano passado: 2015, 2014 e 2013. Permite a seleção de mais de um ano.

**Campos da planilha/csv:**

- ID
- Status: Aprovada, Rejeitada e Aprovada mas autor negou (temos isso? não sei quais são nossos status...)
- Trilha
- Tipo de Sessão
- Público
- Duração
- Título Sessão
- Resumo Sessão
- Mecânica Sessão
- Autor 1
- Sexo Autor 1
- E-mail Autor 1
- Palestras outros anos Autor 1 (Ex de preenchimento: 2014, 2015, 2016. Caso a pessoa nunca tenha palestrado mandar vazio)
- Autor 2
- Sexo Autor 2
- E-mail Autor 2
- Palestras outros anos Autor 2 ( Ex de preenchimento: 2010, 2012. Caso a pessoa nunca tenha palestrado mandar vazio)
- Limite de Participantes (pros mão na massa)
- Tags (separadas por vírgula)

**Utilidades:**
- Compilar informações pra tomada de decisão e análise de desempenho de tipos de sessão, trilhas, durações, etc possibilitando a comparação entre anos;
- Análise de % de novos palestrantes e palestrantes mulheres;
- Rápida e fácil identificação de candidatos pro programa de mentoria (palestrantes de primeira viagem);
- Integração via planilha com o sched;
- Geração de cloud tags com os textos das sessões que sejam consideradas destaque para ajudar no esforço de divulgação da grade;
- Análise de dados da grade para ajudar nos esforços de divulgação da conferência;
- Análise em massa das mecânicas que vamos receber no novo tipo de sessão "exercite sua criatividade!", bem como análise histórica para ver se tem alguma mecênica que podemos aproveitar;

**Importante:**

- Coloquei o limite de 3 anos pra evitar sobrecarga no sistema, não sei se isso seria necessário...
- Optei por fazer uma extração mais pesada e com menos filtros pq o resto eu simplesmente resolvo no excel e aí **assumo** que a codificação seja mais rápida e fácil;
- Se formos gerar no formato .csv usar como separador alguma coisa escrota, tipo "|", pq vírgula e ponto e vírgula tem um monte no meio dos textos de resumo e mecânica.

**Comment by hugocorbucci** [comment]
Não temos a informação de gênero dos nossos usuários (e, por consequência, autores).

**Comment by hugocorbucci** [comment]
Também não vou incluir email dos autores para evitar vazar informações pessoais.

**Comment by hugocorbucci** [comment]
With the changes made on commits 773b824ac55328a10bfc583a3dfc3a6d0e01c143 and 8ef8cbd2c28288f7382147f617c0bb29ac33a2e5, one can now use the APIs to generate all of that information.
Requesting `/api/:year/sessions.json` now provides a list of sessions that were submitted for that year. In the payload, there is a link for further information about the authors with the `/users/:id.json` path which provides other proposals information.

Here is a gist that shows the script I used to generate the CSV using the APIs:
https://gist.github.com/hugocorbucci/9b25e089192cd13987949a3ceea16b44
