### ISSUE TITLE
Problema com usabilidade para adicionar o Gravatar

### ISSUE THREAD

**Issue by mirceiavinter** [agile-alliance-brazil/submissions#224]
![gravatar - funcionou github](https://cloud.githubusercontent.com/assets/19628195/15636960/9f34b354-25e4-11e6-80ef-6b5ae8d07c6a.PNG)
![gravatar - nao funcionou](https://cloud.githubusercontent.com/assets/19628195/15636961/a310713e-25e4-11e6-9c5f-3a0c39447808.PNG)

Problema na usabilidade ao tentar adicionar a foto no perfil utilizando o Gravatar. Criei um gravatar e não consegui linkar a minha foto no perfil do Agile Brazil. Não encontrei nenhuma explicação de como utilizar.

**Comment by hugocorbucci** [comment]
Olá Mirceia,
Se você clicar no ícone que deveria ter sua foto, vê seu perfil. Se clicar em editar, abaixo da foto deveria aparecer um link para alterar sua foto direto no gravatar (http://en.gravatar.com/site/signup/seu%40email.com).
Se tiver uma sugestão de como melhorar essa experiência, ficaria feliz em mudá-la. Mas não tenho ideias agora para resolver isso.

**Comment by hugocorbucci** [comment]
Fechando por enquanto já que não consigo reproduzir o problema.
