### ISSUE TITLE
Problemas no cadastro de usuário - Submissão de palestra

### ISSUE THREAD

**Issue by mirceiavinter** [agile-alliance-brazil/submissions#228]
No cadastro do usuário aparece uma opção para marcar caso haja pretensão de submeter as palestras para a conferência. Porém, ao clicar nesta opção e salvar o perfil, a opção para submeter palestra não é exibida. Além disso, ao editar novamente o perfil, essa opção desaparece e não há a possibilidade de editá-la novamente.
![issue 03](https://cloud.githubusercontent.com/assets/19628195/15637004/8a6f1102-25e5-11e6-8432-075eabf6e29e.PNG)

**Comment by hugocorbucci** [comment]
Oi @mirceiavinter,
A abilidade de submeter propostas não depende apenas dessa caixa. Também precisa estar numa conferência no período de submissão de propostas. Não sei qual ambiente usou para testar mas eu tentei reproduzir aqui em staging (https://submissoes-staging.agilebrazil.com) e não tive problemas.

A opção desaparece porque você já informou que gostaria de ser autora e não tem como deixar de ser. Nada errado até onde consegui ver. Se tiver, mande uma atualização aqui e reabrimos.

Obrigado!
