### ISSUE TITLE
Mudança no idioma do site

### ISSUE THREAD

**Issue by mirceiavinter** [agile-alliance-brazil/submissions#229]
Ao cadastrar o perfil selecionando o idioma Inglês, o site salva as configurações e o site é mostrado em inglês. Porém, ao selecionar "Português" o topo do site, efetuar o logout e logar novamente com o perfil inglês, o site é exibido em português.
![issue 04](https://cloud.githubusercontent.com/assets/19628195/15637073/2362ae36-25e7-11e6-8eaa-40f05dbdfa79.PNG)

**Comment by hugocorbucci** [comment]
Olá Marceia,
Isso não é bem um erro. Se você escolheu estar no menu em Português e deslogou, você ainda está no site em Português. Se fechar a aba e abrir outra e logar, você voltará ao seu idioma de preferência. Mas uma vez que você forçou o sistema para outra linguagem, ele fica nela até perder a informações (que fica na URL no parâmetro locale).
