### ISSUE TITLE
Bug: estouro de limites de caracteres -259

### ISSUE THREAD

**Issue by fabiolimaf** [agile-alliance-brazil/submissions#236]
Após preencher o campo  RESUMO e “estourando” o limite de caracteres (-259), o campo fica bloqueado não sendo possível apagar o conteúdo do mesmo. O comportamento se repete no campo: DESCRIÇÃO COMPLETA, MECÂNICA/PROCESSO, BENEFÍCIOS, EXPERIÊNCIA COM O ASSUNTO.

**Comment by hugocorbucci** [comment]
Resolvido
