### ISSUE TITLE
Melhoria: tradução contéudo campos  Prerequisites e Target audience

### ISSUE THREAD

**Issue by fabiolimaf** [agile-alliance-brazil/submissions#240]
Ao submeter em português e posteriormente acessar a submissão em inglês, os campos: Prerequisites e Target audience, não receberam tradução de conteúdo.

**Comment by hugocorbucci** [comment]
Os campos são de entrada livre. Não tem como traduzí-los automaticamente da mesma forma que não traduzimos título, resumo e outros campos texto.
