### ISSUE TITLE
Melhoria: link quebrado e sobrepondo o sistema de submissão.

### ISSUE THREAD

**Issue by fabiolimaf** [agile-alliance-brazil/submissions#241]
Na página inicial mudar o link **Agile Brazil 2017** para que o mesmo abra em outra aba. O mesmo para o **Regras de Submissão.**

**Comment by hugocorbucci** [comment]
Infelizmente a página inicial é gerada via textile com o texto que os administradores da conferência inserem. E textile não tem  1 forma de abrir um link em outra aba. O jeito é trocar pra markdown e usar HTML.
