### ISSUE TITLE
Filtro de Avaliadores por Status e Trilha de interesse não funciona

### ISSUE THREAD

**Issue by fabiolimaf** [agile-alliance-brazil/submissions#244]
- Ao selecionar o campo status na página de revisores e clicar em filtrar avaliadores, o filtro retorna uma lista com todos os status;

Ao selecionar o campo 'trilha de interesse' na página de revisores e clicar em filtrar avaliadores, o filtro retorna uma lista com todas as trilhas;

**Comment by hugocorbucci** [comment]
Não consegui reproduzir a falha no filtro de trilha.
O de status tava errado mesmo. Resolvi.
