### ISSUE TITLE
Public "Tag Cloud"

### ISSUE THREAD

**Issue by gmotta** [agile-alliance-brazil/submissions#248]
As a volunteer on the Program team, I would like to have a "Tag Cloud" that continuously displays which and how many tags are currently selected for the current submissions so that I can know which topics have more interest.

This will help during submissions and later on building the schedule and reviewing proposals.

**Comment by hugocorbucci** [comment]
Should be live.
Conference have to be configured to show the tag cloud where they want.
All you need is to drop a content like:
```
div(tagcloud). &nbsp;
```

In any page and the tag cloud will be loaded.

**Comment by hugocorbucci** [comment]
Got things handled better by #257 so I'm gonna call this done for now.
