### ISSUE TITLE
Removal of tracks from the submission system

### ISSUE THREAD

**Issue by gmotta** [agile-alliance-brazil/submissions#249]
As a volunteer on the Program team, I would like tracks to be removed so that it decreases the complexity of submissions and removes the need of grouping sessions later on based on a submission decision.

We had several discussions on this topic.
Based on the typeform with ~120 answers, people do not look at "Track" in order to decide if they will attend the conference or a session.

**Comment by hugocorbucci** [comment]
More work needed here once we get past the submissions part.
Reviewers were track based so we'll need to handle all of that. For submission opening though, this should be good.

**Comment by hugocorbucci** [comment]
Done in https://github.com/agile-alliance-brazil/submissions/commit/e29e54a9753e47908b5cfb11cd4b0cbcf9ada019 and subsequent commits
