### ISSUE TITLE
Limit the number of proposals an user is able to submit to 3

### ISSUE THREAD

**Issue by gmotta** [agile-alliance-brazil/submissions#250]
As a volunteer on the Program team, I would like the ability to limit the number of proposals an user is able to submit so that we get only the best ideas from each author, we have enough sessions to review without wasting time on desperate speakers,

Nice to have:
As a potential speaker, I want the ability to delete or cancel a session I submitted so that I can work on a better proposal.

Questions:
If Mary makes a submission and adds John as a co-speaker, it only counts on Mary quote of 3?
- My personal assumption: yes.

**Comment by hugocorbucci** [comment]
Made it so that Mary and John's both counts go up and therefore add to limit.
John can log in and edit the sessions with Mary to remove himself if he wants to. Handled delete/cancel in #253

**Comment by gmotta** [comment]
Fixed. Tested in staging.
