### ISSUE TITLE
As a person who submits a proposal, I want to be able to delete one of my proposed sessions

### ISSUE THREAD

**Issue by gmotta** [agile-alliance-brazil/submissions#253]
As a person who submits a proposal, I want to be able to delete one of my proposed sessions.

More info:
Given we are adding the limit of 3 sessions per user, I would like to ability to cancel/delete proposals that I open by mistake or decide to not move forward with.

**Comment by hugocorbucci** [comment]
Should be available in the session show page for the authors.

**Comment by gmotta** [comment]
Fixed! Testing in staging for 2018.
