### ISSUE TITLE
Year-bound search by tags

### ISSUE THREAD

**Issue by ceci** [agile-alliance-brazil/submissions#259]
**In order to...** stop getting frustrated and confused when I search for tags and find no results because that tag isn't even available for this year's submissions
**As a...** author or reviewer
**I want...** the tag search on sessions lists to suggest only the tags that are available for the current year.

**Comment by ceci** [comment]
I would also like to request a minor CSS improvement, that would be removing the list style, and maybe adding some padding to the tags suggestions dropdown.

This looks good, IMO:
```
li.ui-menu-item {
    list-style: none;
    padding: 0.2em 0.5em 0.2em;
}
```

**Comment by hugocorbucci** [comment]
Should be fine now according to @ceci
