### ISSUE TITLE
Período para feedback prévio a período de revisões

### ISSUE THREAD

**Issue by ehernandez** [agile-alliance-brazil/submissions#285]
Como chair de programa
Eu quero que o sistema possua duas datas distintas de deadline
Para que após o encerramento do período de novas submissões, as propostas enviadas ainda possam sofrer modificações até uma data onde aí então elas serão avaliadas pelos revisores

----
Exemplo:
- Novas submissões possíveis no período de 1 a 30 de abril
- Entre 1 a 31 de maio, as submissões enviadas podem sofrer alterações 
- Entre 1 a 30 de junho, as submissões não podem sofrer alterações e serão avaliadas pelo grupo revisor

**Comment by hugocorbucci** [comment]
Está em staging. Deixei submissões novas até amanhã e edições até o fim de semana em staging para testes.
