### ISSUE TITLE
Character counting is wrong

### ISSUE THREAD

**Issue by dtsato** [agile-alliance-brazil/submissions#65]
O contador de caracteres da descrição completa está com algum problema e está acusando números falsos. O screenshot do Adriano (em anexo) tá marcando que ainda tem 18 caracteres de espaço e ele não conseguia mais escrever nada.

Passando um contador de caracteres no texto dele, tinha 2434 caracteres... i.e., tinha passado 34 do que teoricamente podia.

**Comment by celsoMartins** [comment]
![image](https://cloud.githubusercontent.com/assets/214322/15089667/3fb71adc-13df-11e6-8a70-ded930287ecf.png)

**Comment by hugocorbucci** [comment]
Since we got no other complains... closing this

**Comment by hugocorbucci** [comment]
Had to revert this commit since it wasn't taking into account fields with minimums instead of maximums.

**Comment by hugocorbucci** [comment]
Gonna close this one as part of #236
